# Generated by Django 2.1.5 on 2019-02-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songeditor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='date',
        ),
    ]
