# Generated by Django 2.1.5 on 2019-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songeditor', '0004_auto_20190216_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(max_length=10000),
        ),
    ]
