# Generated by Django 2.1.5 on 2019-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songeditor', '0005_auto_20190303_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='direction',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
